bs: 64 # batch size
data:
    path: '~/data/mc_density_data/comb_am_rp.npy'
lr_max: null # Maximum learning rate. If none, it will be computed automatically
mmap: True,
n_epoch: 25 # Number of epochs to train for
seed: 42 # random seed
tmp_folder: 'tmp' # Folder to store temporary files
wandb:
  enabled: False # To use it, the environment variable WANDB_API_KEY must be set
  log_learner: False # Log learner to wandb
  mode: 'offline' # 'online' or 'offline' for wandb
  group: null # Useful to group runs that belong to the same optuna study
  project: 'mocatml' # Name of wandb project