arch:
  name: 'TSiT' # see 'all_arch_names' in tsai
  config_file: null # Absolute, or relative to the execution environment. Null for default
lookback: 10 # number of previous steps to consider
horizon: 1 # number of steps into the future
stride: 1 # number of steps between two consecutive windows