# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs_lib/utils.ipynb.

# %% auto 0
__all__ = ['convert_uuids_to_indices']

# %% ../nbs_lib/utils.ipynb 2
import os
import re

# %% ../nbs_lib/utils.ipynb 3
def convert_uuids_to_indices():
    cuda_visible_devices = os.environ.get("CUDA_VISIBLE_DEVICES", "")
    uuids = re.findall(r"\b[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}\b", cuda_visible_devices)

    if uuids:
        indices = [str(i) for i in range(len(uuids))]
        os.environ["CUDA_VISIBLE_DEVICES"] = ",".join(indices)
