# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs_lib/models.utils.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs_lib/models.utils.ipynb 3
from .conv_rnn import *
from fastcore.all import *
from fastai.vision.all import Learner

# %% ../../nbs_lib/models.utils.ipynb 4
@patch
@delegates(Learner.get_preds)
def get_preds_iterative(self:Learner, n_iter=1, **kwargs):
    "Call get preds iteratively"
    p, _ = self.get_preds(**kwargs)
    for _ in range(n_iter-1):
        p = self.model(p)
    return p
